# Generated by Django 5.2.8 on 2025-11-27 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="cover_image",
        ),
        migrations.AddField(
            model_name="book",
            name="cover_image_url",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
