# Generated by Django 5.2.8 on 2025-11-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_book_cover_image_book_cover_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="slug",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
