# Generated by Django 5.2.8 on 2025-11-28 01:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_book_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_image_url",
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="book",
            unique_together={("added_by", "title", "is_available")},
        ),
    ]
