# Generated by Django 5.2.8 on 2025-11-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_book_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("telebirr", "Telebirr"),
                    ("abyssinia", "Bank of Abyssinia"),
                    ("bank", "Bank Transfer"),
                    ("cash", "Cash"),
                ],
                default="telebirr",
                max_length=20,
            ),
        ),
    ]
