# Generated by Django 5.2.8 on 2025-12-01 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_book_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ZCoinCalculatorSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "classics_base",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=10),
                ),
                (
                    "nonfiction_base",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
                ),
                (
                    "fiction_base",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
                ),
                (
                    "contemporary_base",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
                ),
                (
                    "academic_base",
                    models.DecimalField(decimal_places=2, default=35.0, max_digits=10),
                ),
                (
                    "children_base",
                    models.DecimalField(decimal_places=2, default=18.0, max_digits=10),
                ),
                (
                    "reference_base",
                    models.DecimalField(decimal_places=2, default=40.0, max_digits=10),
                ),
                (
                    "excellent_multiplier",
                    models.DecimalField(decimal_places=2, default=1.5, max_digits=5),
                ),
                (
                    "good_multiplier",
                    models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
                ),
                (
                    "fair_multiplier",
                    models.DecimalField(decimal_places=2, default=0.7, max_digits=5),
                ),
                (
                    "poor_multiplier",
                    models.DecimalField(decimal_places=2, default=0.4, max_digits=5),
                ),
                (
                    "hardcover_bonus",
                    models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
                ),
                (
                    "dust_jacket_bonus",
                    models.DecimalField(decimal_places=2, default=15.0, max_digits=10),
                ),
                (
                    "no_cover_penalty",
                    models.DecimalField(decimal_places=2, default=-5.0, max_digits=10),
                ),
                (
                    "has_images_bonus",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                (
                    "has_original_dust_jacket",
                    models.DecimalField(decimal_places=2, default=8.0, max_digits=10),
                ),
                (
                    "is_first_edition_bonus",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
                ),
                (
                    "is_signed_bonus",
                    models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
                ),
                (
                    "min_zcoin",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
                ),
                (
                    "max_zcoin",
                    models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
                ),
                (
                    "zcoin_to_birr_rate",
                    models.DecimalField(decimal_places=2, default=0.1, max_digits=10),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "ZCoin Calculator Settings",
                "verbose_name_plural": "ZCoin Calculator Settings",
            },
        ),
        migrations.CreateModel(
            name="ZCoinCalculationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=50)),
                ("condition", models.CharField(max_length=20)),
                ("cover_type", models.CharField(blank=True, max_length=20, null=True)),
                ("has_images", models.BooleanField(default=False)),
                ("has_dust_jacket", models.BooleanField(default=False)),
                ("is_first_edition", models.BooleanField(default=False)),
                ("is_signed", models.BooleanField(default=False)),
                ("base_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "condition_multiplier",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "bonuses",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "calculated_zcoin",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("final_zcoin", models.DecimalField(decimal_places=2, max_digits=10)),
                ("manual_override", models.BooleanField(default=False)),
                (
                    "manual_zcoin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "manual_price_birr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zcoin_calculations",
                        to="core.book",
                    ),
                ),
                (
                    "calculated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
