# Generated by Django 5.2.8 on 2025-12-01 14:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_zcoincalculatorsettings_zcoincalculationlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="assessed_condition",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "Excellent"),
                    ("good", "Good"),
                    ("fair", "Fair"),
                    ("poor", "Poor"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="cover_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("hardcover", "Hardcover"),
                    ("softcover", "Softcover"),
                    ("paperback", "Paperback"),
                    ("dust_jacket", "Dust Jacket"),
                    ("no_cover", "No Cover"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="has_dust_jacket",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="has_images",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="is_first_edition",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="is_signed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="book",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Admin notes about the book condition"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("non-fiction", "Non-Fiction"),
                    ("classics", "Classics"),
                    ("contemporary", "Contemporary"),
                    ("academic", "Academic"),
                    ("children", "Children's"),
                    ("reference", "Reference"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="is_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="price_birr",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("reviewed", "Reviewed"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="zcoin_value",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="swaprequest",
            name="user_book_genre",
            field=models.CharField(
                choices=[
                    ("fiction", "Fiction"),
                    ("non-fiction", "Non-Fiction"),
                    ("classics", "Classics"),
                    ("contemporary", "Contemporary"),
                    ("academic", "Academic"),
                    ("children", "Children's"),
                    ("reference", "Reference"),
                ],
                max_length=50,
            ),
        ),
    ]
