# Generated by Django 5.2.8 on 2025-12-01 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_book_assessed_condition_book_cover_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="zcoincalculatorsettings",
            name="has_original_dust_jacket",
        ),
        migrations.AddField(
            model_name="book",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
    ]
