# Generated by Django 5.2.8 on 2025-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_book_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zcoincalculationlog",
            name="base_value",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
