# Generated by Django 5.2.8 on 2025-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_zcoincalculationlog_base_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zcoincalculationlog",
            name="condition_multiplier",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
