# Generated by Django 5.2.8 on 2025-12-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_commodity_commoditypurchase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commodity",
            name="image_url",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
